# Generated by Django 3.0.7 on 2020-06-30 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DexUsername', models.CharField(max_length=255)),
                ('DexPassword', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=2083)),
                ('manga_url', models.CharField(max_length=2083)),
                ('manga_id', models.IntegerField()),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=2083)),
                ('manga_url', models.CharField(max_length=2083)),
                ('manga_id', models.IntegerField()),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chapter_url', models.CharField(max_length=2083)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga')),
            ],
        ),
    ]
