# Generated by Django 3.0.7 on 2020-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20200630_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
