# Generated by Django 3.0.7 on 2020-07-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_auto_20200703_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='description',
        ),
        migrations.RemoveField(
            model_name='search',
            name='description',
        ),
    ]
