# Generated by Django 3.0.7 on 2020-07-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_auto_20200722_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manga',
            unique_together={('name', 'type')},
        ),
    ]
